spring:
    profiles:
        active:
        - dev
---
server:
    port: 8001
    
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml
    type-aliases-package: com.atguigu.springcloud.entities
    mapper-locations:
    - classpath:mybatis/mapper/**/*.xml
    
spring:
    profiles: dev
    application:
        name: microservicecloud-dept
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: org.gjt.mm.mysql.Driver
        url: jdbc:mysql://192.168.137.1:3306/cloudDB01
        username: sa
        password: 123
        dbcp2:
            min-idle: 5
            initial-size: 5
            max-total: 5
            max-wait-millis: 200
        
eureka:
    client:
        service-url: 
            defaultZone: http://localhost:7001/eureka
    instance:
        instance-id: microservicecloud-dept8001
        prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
    app.name: atguigu-microservicecloud
    company.name: www.fsfzjq.com
    build.artifactId: ￥project.artifactId￥
    build.version: ￥project.version￥
---
spring:
    profiles: test
    application:
        name: bbbbbbbbbbbbbbbbbbb