spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: aaaaaaaaaaaaaaaaaa
---
spring:
    profiles: test
    application:
        name: bbbbbbbbbbbbbbbbbbb